from camera import make_camera_controls
from fileControls import make_file_controls
from model import make_model_controls
from parameters import make_parameter_controls
from sidebar import  make_sidebar